name: Deploy Frontend to Azure

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          CI=false npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: .

      - name: Debug - List root
        run: |
          echo "ROOT:"
          ls -la
          echo "CONTENIDO FRONTEND-BUILD:"
          ls -la frontend-build || true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: btsweb
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F3FCF3824024266AC2221BD7C46AE2B }}
          package: ./frontend-build