name: Build and deploy React app to Azure Web App - btsweb

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React app
        working-directory: ./frontend
        run: npm run build
        env:
          CI: false

      - name: Prepare app for deployment
        run: |
          mkdir app
          cp -r ./frontend/build/* ./app/

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: app/


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: .

      - name: Verify downloaded files
        run: ls -R

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'btsweb'
          publish-profile: ${{ secrets.DEVELOPMENT }}
          package: .
